(package "msgu"
         "0.1.0"
         "Utility functions help output the messages")

(website-url "https://github.com/jcs-elpa/msgu")
(keywords "lisp")

(package-file "msgu.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")

(depends-on "emacs" "26.1")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
